# Configurations
title:            Ben's Revision
longtitle:        Ben's Revision
author:           Ben Worthington
email:            ben@wrth.me
description: >
  Personal revision notes for my GCSEs. Feel free to use for yourself if you like.
version:          1.0
gitbook_version:  3.2.3

url:              'https://revise.wrth.me'
baseurl:          '/revise'
rss:              RSS

toc:
  enabled: true
  h_min: 1
  h_max: 3

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

remote_theme: GitBook

# Permalinks
permalink:        /:title:output_ext

exclude:
  - _drafts

destination:      ./_site
incremental:      false
regenerate:       true
